package Components;

import java.util.HashMap;

public class CountryMap {

    private static HashMap<String, String> countryMap = CountryMap.createCountryMap();

    public static String getCountryName(String countryCode){
        CountryMap countryMap = new CountryMap();
        return countryMap.countryMap.get(countryCode);
    }
    private static HashMap<String,String> createCountryMap(){
        HashMap<String,String> countryMap = new HashMap<String,String>();
        countryMap.put("AF", "Afghanistan");
        countryMap.put("AL", "Albania");
        countryMap.put("DZ", "Algeria");
        countryMap.put("AS", "American Samoa");
        countryMap.put("AD", "Andorra");
        countryMap.put("AO", "Angola");
        countryMap.put("AI", "Anguilla");
        countryMap.put("AQ", "Antarctica");
        countryMap.put("AG", "Antigua and Barbuda");
        countryMap.put("AR", "Argentina");
        countryMap.put("AM", "Armenia");
        countryMap.put("AW", "Aruba");
        countryMap.put("AU", "Australia");
        countryMap.put("AT", "Austria");
        countryMap.put("AZ", "Azerbaijan");
        countryMap.put("BS", "Bahamas");
        countryMap.put("BH", "Bahrain");
        countryMap.put("BD", "Bangladesh");
        countryMap.put("BB", "Barbados");
        countryMap.put("BY", "Belarus");
        countryMap.put("BE", "Belgium");
        countryMap.put("BZ", "Belize");
        countryMap.put("BJ", "Benin");
        countryMap.put("BM", "Bermuda");
        countryMap.put("BT", "Bhutan");
        countryMap.put("BO", "Bolivia");
        countryMap.put("BA", "Bosnia and Herzegovina");
        countryMap.put("BW", "Botswana");
        countryMap.put("BR", "Brazil");
        countryMap.put("BN", "Brunei");
        countryMap.put("BG", "Bulgaria");
        countryMap.put("BF", "Burkina Faso");
        countryMap.put("BI", "Burundi");
        countryMap.put("CV", "Cabo Verde");
        countryMap.put("KH", "Cambodia");
        countryMap.put("CM", "Cameroon");
        countryMap.put("CA", "Canada");
        countryMap.put("KY", "Cayman Islands");
        countryMap.put("CF", "Central African Republic");
        countryMap.put("TD", "Chad");
        countryMap.put("CL", "Chile");
        countryMap.put("CN", "China");
        countryMap.put("CO", "Colombia");
        countryMap.put("KM", "Comoros");
        countryMap.put("CG", "Congo");
        countryMap.put("CD", "Congo (DRC)");
        countryMap.put("CR", "Costa Rica");
        countryMap.put("CI", "Côte d'Ivoire");
        countryMap.put("HR", "Croatia");
        countryMap.put("CU", "Cuba");
        countryMap.put("CY", "Cyprus");
        countryMap.put("CZ", "Czechia");
        countryMap.put("DK", "Denmark");
        countryMap.put("DJ", "Djibouti");
        countryMap.put("DM", "Dominica");
        countryMap.put("DO", "Dominican Republic");
        countryMap.put("EC", "Ecuador");
        countryMap.put("EG", "Egypt");
        countryMap.put("SV", "El Salvador");
        countryMap.put("GQ", "Equatorial Guinea");
        countryMap.put("ER", "Eritrea");
        countryMap.put("EE", "Estonia");
        countryMap.put("SZ", "Eswatini");
        countryMap.put("ET", "Ethiopia");
        countryMap.put("FJ", "Fiji");
        countryMap.put("FI", "Finland");
        countryMap.put("FR", "France");
        countryMap.put("GA", "Gabon");
        countryMap.put("GM", "Gambia");
        countryMap.put("GE", "Georgia");
        countryMap.put("DE", "Germany");
        countryMap.put("GH", "Ghana");
        countryMap.put("GR", "Greece");
        countryMap.put("GD", "Grenada");
        countryMap.put("GU", "Guam");
        countryMap.put("GT", "Guatemala");
        countryMap.put("GN", "Guinea");
        countryMap.put("GW", "Guinea-Bissau");
        countryMap.put("GY", "Guyana");
        countryMap.put("HT", "Haiti");
        countryMap.put("HN", "Honduras");
        countryMap.put("HU", "Hungary");
        countryMap.put("IS", "Iceland");
        countryMap.put("IN", "India");
        countryMap.put("ID", "Indonesia");
        countryMap.put("IR", "Iran");
        countryMap.put("IQ", "Iraq");
        countryMap.put("IE", "Ireland");
        countryMap.put("IL", "Israel");
        countryMap.put("IT", "Italy");
        countryMap.put("JM", "Jamaica");
        countryMap.put("JP", "Japan");
        countryMap.put("JO", "Jordan");
        countryMap.put("KZ", "Kazakhstan");
        countryMap.put("KE", "Kenya");
        countryMap.put("KI", "Kiribati");
        countryMap.put("KW", "Kuwait");
        countryMap.put("KG", "Kyrgyzstan");
        countryMap.put("LA", "Laos");
        countryMap.put("LV", "Latvia");
        countryMap.put("LB", "Lebanon");
        countryMap.put("LS", "Lesotho");
        countryMap.put("LR", "Liberia");
        countryMap.put("LY", "Libya");
        countryMap.put("LI", "Liechtenstein");
        countryMap.put("LT", "Lithuania");
        countryMap.put("LU", "Luxembourg");
        countryMap.put("MG", "Madagascar");
        countryMap.put("MW", "Malawi");
        countryMap.put("MY", "Malaysia");
        countryMap.put("MV", "Maldives");
        countryMap.put("ML", "Mali");
        countryMap.put("MT", "Malta");
        countryMap.put("MH", "Marshall Islands");
        countryMap.put("MR", "Mauritania");
        countryMap.put("MU", "Mauritius");
        countryMap.put("MX", "Mexico");
        countryMap.put("FM", "Micronesia");
        countryMap.put("MD", "Moldova");
        countryMap.put("MC", "Monaco");
        countryMap.put("MN", "Mongolia");
        countryMap.put("ME", "Montenegro");
        countryMap.put("MA", "Morocco");
        countryMap.put("MZ", "Mozambique");
        countryMap.put("MM", "Myanmar");
        countryMap.put("NA", "Namibia");
        countryMap.put("NR", "Nauru");
        countryMap.put("NP", "Nepal");
        countryMap.put("NL", "Netherlands");
        countryMap.put("NZ", "New Zealand");
        countryMap.put("NI", "Nicaragua");
        countryMap.put("NE", "Niger");
        countryMap.put("NG", "Nigeria");
        countryMap.put("KP", "North Korea");
        countryMap.put("MK", "North Macedonia");
        countryMap.put("NO", "Norway");
        countryMap.put("OM", "Oman");
        countryMap.put("PK", "Pakistan");
        countryMap.put("PW", "Palau");
        countryMap.put("PA", "Panama");
        countryMap.put("PG", "Papua New Guinea");
        countryMap.put("PY", "Paraguay");
        countryMap.put("PE", "Peru");
        countryMap.put("PH", "Philippines");
        countryMap.put("PL", "Poland");
        countryMap.put("PT", "Portugal");
        countryMap.put("QA", "Qatar");
        countryMap.put("RO", "Romania");
        countryMap.put("RU", "Russia");
        countryMap.put("RW", "Rwanda");
        countryMap.put("WS", "Samoa");
        countryMap.put("SM", "San Marino");
        countryMap.put("ST", "São Tomé and Príncipe");
        countryMap.put("SA", "Saudi Arabia");
        countryMap.put("SN", "Senegal");
        countryMap.put("RS", "Serbia");
        countryMap.put("SC", "Seychelles");
        countryMap.put("SL", "Sierra Leone");
        countryMap.put("SG", "Singapore");
        countryMap.put("SK", "Slovakia");
        countryMap.put("SI", "Slovenia");
        countryMap.put("SB", "Solomon Islands");
        countryMap.put("SO", "Somalia");
        countryMap.put("ZA", "South Africa");
        countryMap.put("KR", "South Korea");
        countryMap.put("SS", "South Sudan");
        countryMap.put("ES", "Spain");
        countryMap.put("LK", "Sri Lanka");
        countryMap.put("SD", "Sudan");
        countryMap.put("SR", "Suriname");
        countryMap.put("SE", "Sweden");
        countryMap.put("CH", "Switzerland");
        countryMap.put("SY", "Syria");
        countryMap.put("TW", "Taiwan");
        countryMap.put("TJ", "Tajikistan");
        countryMap.put("TZ", "Tanzania");
        countryMap.put("TH", "Thailand");
        countryMap.put("TL", "Timor-Leste");
        countryMap.put("TG", "Togo");
        countryMap.put("TO", "Tonga");
        countryMap.put("TT", "Trinidad and Tobago");
        countryMap.put("TN", "Tunisia");
        countryMap.put("TR", "Turkey");
        countryMap.put("TM", "Turkmenistan");
        countryMap.put("TV", "Tuvalu");
        countryMap.put("UG", "Uganda");
        countryMap.put("UA", "Ukraine");
        countryMap.put("AE", "United Arab Emirates");
        countryMap.put("GB", "United Kingdom");
        countryMap.put("US", "United States");
        countryMap.put("UY", "Uruguay");
        countryMap.put("UZ", "Uzbekistan");
        countryMap.put("VU", "Vanuatu");
        countryMap.put("VA", "Vatican City");
        countryMap.put("VE", "Venezuela");
        countryMap.put("VN", "Vietnam");
        countryMap.put("YE", "Yemen");
        countryMap.put("ZM", "Zambia");
        countryMap.put("ZW", "Zimbabwe");

        return countryMap;
    }


}
